# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab2_kg.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 610)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.awidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.awidget.sizePolicy().hasHeightForWidth())
        self.awidget.setSizePolicy(sizePolicy)
        self.awidget.setMinimumSize(QtCore.QSize(0, 250))
        self.awidget.setObjectName("awidget")
        self.verticalLayout.addWidget(self.awidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.cwidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cwidget.sizePolicy().hasHeightForWidth())
        self.cwidget.setSizePolicy(sizePolicy)
        self.cwidget.setMinimumSize(QtCore.QSize(0, 250))
        self.cwidget.setObjectName("cwidget")
        self.verticalLayout_2.addWidget(self.cwidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioT = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioT.setObjectName("radioT")
        self.horizontalLayout_2.addWidget(self.radioT)
        self.radioC = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioC.setObjectName("radioC")
        self.horizontalLayout_2.addWidget(self.radioC)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioCentral = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioCentral.setObjectName("radioCentral")
        self.horizontalLayout_3.addWidget(self.radioCentral)
        self.radioOrhogonal = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioOrhogonal.setObjectName("radioOrhogonal")
        self.horizontalLayout_3.addWidget(self.radioOrhogonal)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_15.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_15.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_15.addWidget(self.label_22)
        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.xSlider = QtWidgets.QSlider(self.groupBox_5)
        self.xSlider.setMinimumSize(QtCore.QSize(250, 0))
        self.xSlider.setMinimum(0)
        self.xSlider.setMaximum(100)
        self.xSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xSlider.setInvertedAppearance(False)
        self.xSlider.setInvertedControls(False)
        self.xSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.xSlider.setObjectName("xSlider")
        self.verticalLayout_11.addWidget(self.xSlider)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.ySlider = QtWidgets.QSlider(self.groupBox_5)
        self.ySlider.setMinimumSize(QtCore.QSize(250, 0))
        self.ySlider.setMinimum(0)
        self.ySlider.setMaximum(100)
        self.ySlider.setOrientation(QtCore.Qt.Horizontal)
        self.ySlider.setInvertedAppearance(False)
        self.ySlider.setInvertedControls(False)
        self.ySlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.ySlider.setObjectName("ySlider")
        self.verticalLayout_16.addWidget(self.ySlider)
        self.verticalLayout_10.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.verticalLayout_17.addLayout(self.horizontalLayout_13)
        self.zSlider = QtWidgets.QSlider(self.groupBox_5)
        self.zSlider.setMinimumSize(QtCore.QSize(250, 0))
        self.zSlider.setMinimum(0)
        self.zSlider.setMaximum(100)
        self.zSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zSlider.setInvertedAppearance(False)
        self.zSlider.setInvertedControls(False)
        self.zSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.zSlider.setObjectName("zSlider")
        self.verticalLayout_17.addWidget(self.zSlider)
        self.verticalLayout_10.addLayout(self.verticalLayout_17)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.horizontalLayout_6.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(55, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(55, 16777215))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.xTField = QtWidgets.QLineEdit(self.groupBox)
        self.xTField.setMinimumSize(QtCore.QSize(35, 20))
        self.xTField.setMaximumSize(QtCore.QSize(35, 20))
        self.xTField.setAlignment(QtCore.Qt.AlignCenter)
        self.xTField.setReadOnly(True)
        self.xTField.setObjectName("xTField")
        self.verticalLayout_3.addWidget(self.xTField)
        self.yTField = QtWidgets.QLineEdit(self.groupBox)
        self.yTField.setMinimumSize(QtCore.QSize(35, 20))
        self.yTField.setMaximumSize(QtCore.QSize(35, 20))
        self.yTField.setAlignment(QtCore.Qt.AlignCenter)
        self.yTField.setReadOnly(True)
        self.yTField.setObjectName("yTField")
        self.verticalLayout_3.addWidget(self.yTField)
        self.zTField = QtWidgets.QLineEdit(self.groupBox)
        self.zTField.setMinimumSize(QtCore.QSize(35, 20))
        self.zTField.setMaximumSize(QtCore.QSize(35, 20))
        self.zTField.setAlignment(QtCore.Qt.AlignCenter)
        self.zTField.setReadOnly(True)
        self.zTField.setObjectName("zTField")
        self.verticalLayout_3.addWidget(self.zTField)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(55, 55))
        self.groupBox_4.setMaximumSize(QtCore.QSize(55, 16777215))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.xCField = QtWidgets.QLineEdit(self.groupBox_4)
        self.xCField.setMinimumSize(QtCore.QSize(35, 20))
        self.xCField.setMaximumSize(QtCore.QSize(35, 20))
        self.xCField.setAlignment(QtCore.Qt.AlignCenter)
        self.xCField.setReadOnly(True)
        self.xCField.setObjectName("xCField")
        self.verticalLayout_4.addWidget(self.xCField)
        self.yCField = QtWidgets.QLineEdit(self.groupBox_4)
        self.yCField.setMinimumSize(QtCore.QSize(35, 20))
        self.yCField.setMaximumSize(QtCore.QSize(35, 20))
        self.yCField.setAlignment(QtCore.Qt.AlignCenter)
        self.yCField.setReadOnly(True)
        self.yCField.setObjectName("yCField")
        self.verticalLayout_4.addWidget(self.yCField)
        self.zCField = QtWidgets.QLineEdit(self.groupBox_4)
        self.zCField.setMinimumSize(QtCore.QSize(35, 20))
        self.zCField.setMaximumSize(QtCore.QSize(35, 20))
        self.zCField.setAlignment(QtCore.Qt.AlignCenter)
        self.zCField.setReadOnly(True)
        self.zCField.setObjectName("zCField")
        self.verticalLayout_4.addWidget(self.zCField)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.xSlider.valueChanged['int'].connect(MainWindow.on_x_changed)
        self.ySlider.valueChanged['int'].connect(MainWindow.on_y_changed)
        self.zSlider.valueChanged['int'].connect(MainWindow.on_z_changed)
        self.radioT.clicked.connect(MainWindow.on_radio_t_clicked)
        self.radioC.clicked.connect(MainWindow.on_radio_c_clicked)
        self.radioCentral.clicked.connect(MainWindow.on_radio_central_clicked)
        self.radioOrhogonal.clicked.connect(MainWindow.on_radio_orthogonal_clicked)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Афинные преобразования и аксонометрическое изображение точки"))
        self.label.setText(_translate("MainWindow", "Аксонометрический чертеж"))
        self.label_2.setText(_translate("MainWindow", "Комплексный чертеж"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Выбранная точка"))
        self.radioT.setText(_translate("MainWindow", "Точка T"))
        self.radioC.setText(_translate("MainWindow", "Точка C (камера)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Проецирование"))
        self.radioCentral.setText(_translate("MainWindow", "Центральное"))
        self.radioOrhogonal.setText(_translate("MainWindow", "Ортогональное"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Изменение координат"))
        self.label_20.setText(_translate("MainWindow", "X:"))
        self.label_21.setText(_translate("MainWindow", "Y:"))
        self.label_22.setText(_translate("MainWindow", "Z:"))
        self.label_18.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "100"))
        self.label_23.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "100"))
        self.label_25.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "100"))
        self.groupBox.setTitle(_translate("MainWindow", "T"))
        self.groupBox_4.setTitle(_translate("MainWindow", "C"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))


